[project]
name = "extract-data-from-video-banner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "opencv-python-headless>=4.10.0.84",
    "pytesseract>=0.3.13",
]
